IBAN validation, remember rejected content
svsticky/digidecs pull request #10
Opened 2017-05-15 14:44 UTC by spasticVerbalizer

Fixes #7

IBAN validation works, all entries with invalid IBAN-numbers (test: NL00TEST0123456789, valid is NL13TEST0123456789) are rejected, and the contents of the form are kept as well (to ease the process of accepting you're wrong) so that's nice.

2017-05-15 14:45 UTC, spasticVerbalizer commented
Currently live at https://digidecs.dev.svsticky.nl

2017-05-15 14:53 UTC, tomwassenberg commented
Not really related, but maybe you can also add a label for the submit button, if you're polishing stuff anyway ;)

2017-05-15 14:56 UTC, spasticVerbalizer commented
Good one, "Ik wil mijn geld terug!"?

2017-05-15 14:58 UTC, tomwassenberg commented
For brevity I'd say "Geef geld" ;)

2017-05-15 15:00 UTC, spasticVerbalizer commented
Done

2017-05-15 16:09 UTC, duijf requested changes
Didn't look at this too closely, just one thing that definitely needs fixing (I don't know if I did it properly in other places so feel free to shame me about those :man_shrugging:)

2017-05-15 16:09 UTC, duijf commented on index.php
> +		return 'value="'. $_POST[$field] . '"';
This needs to be sanitized

2017-05-16 08:05 UTC, spasticVerbalizer commented on index.php
> +		return 'value="'. $_POST[$field] . '"';
`htmlspecialchars`?

2017-05-16 08:29 UTC, spasticVerbalizer commented on index.php
> +		return 'value="'. $_POST[$field] . '"';
Done, nu actief op dev

2017-05-19 08:37 UTC, spasticVerbalizer commented
@duijf Escaped enough?

2017-06-01 19:50 UTC, merged